### ISSUE TITLE
Saved digimemory freezes the game

### ISSUE THREAD

**Issue by wiitation** [SydMontague/DecodeRandomizer#1]
Not exactly freeze it, but whenever you enter digimemory with a saved digimon, game starts working pretty badly and it wont let you save the game, it keeps loading and loading, models doesnt load either on either email or digimemory.

Also, summoning doesnt work properly, when pressing summon button, game freezes, music running, animations running, everything good, but it stays still there and doesnt do anything

**Comment by SydMontague** [comment]
That sounds like the ROM extraction or rebuild failed somewhere. Could you try rebuilding the ROM from a fresh dump of the original game?

If it keeps happening, could you please export the randomization settings you used?

**Comment by wiitation** [comment]
it was the rebuilding, yeah

working fine now, except for the save file that even the new ROM cant load properly, keeps crashing as usual
